name: 🚀 Android Release

on:
  push:
    branches: [main]

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    # if: ${{ contains(github.event.head_commit.message, '#app') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.10.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
      - name: Create version.txt with NuGetVersionV2
        run: echo ${{ steps.gitversion.outputs.NuGetVersionV2  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
  build:
    name: Build APK and Create release
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - name: build APK
        run: |
          cd app
          echo ${{ secrets.JKS }} | base64 --decode > android/key.jks
          echo ${{ secrets.KEY }} | base64 --decode > android/key.properties
          flutter pub get
          flutter build apk --release --split-per-abi
          mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/TheSiS_App-x86_64.apk
          mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/TheSiS_App-v8a.apk
          mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/TheSiS_App-v7a.apk
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
